name: Start CI Build
description: Start CI Build

inputs:
  github-token:
    description: 'Github token used to create PR comments'
    required: true
  ci-project:
    description: 'Name of the CI project to track in LocalStack Cloud'
    required: false

runs:
  using: composite
  steps:
    - name: Save PR number
      shell: bash
      run: echo ${{ github.event.number }} > ./pr-id.txt

    - name: Upload PR number
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: pr-id
        path: ./pr-id.txt

    - name: Create initial PR comment
      uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
      with:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        header: localstack-preview
        message: |
          ⚡️ Running CI build with LocalStack ...
