name: 'Setup LocalStack'
description: 'Sets up LocalStack CLI in your GitHub Actions workflow.'
author: 'Harsh Mishra'

branding:
  icon: 'code'
  color: 'white'

inputs:
  image-tag:
    description: 'Tag of the LocalStack Docker image to use'
    required: true
    default: 'latest'
  install-awslocal:
    description: 'Whether to install the `awslocal` CLI into the environment'
    required: true
    default: 'true'
  use-pro:
    description: 'Whether to use LocalStack Pro (requires a valid API key)'
    required: false
    default: 'false'
  configuration:
    description: 'Configuration variables to use for LocalStack'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - 
      run: |
        pip install pyopenssl -U

        if [ "$USE_PRO" = true ]; then
          docker pull localstack/localstack-pro:"$IMAGE_TAG"
          CONFIGURATION="$CONFIGURATION DNS_ADDRESS=0"
        else
          docker pull localstack/localstack:"$IMAGE_TAG"
        fi

        pip install localstack
        eval "${CONFIGURATION} localstack start -d"

        localstack wait -t 30
        if [ "$INSTALL_AWSLOCAL" = true ]; then
          pip install awscli-local[ver1]
        fi
      shell: bash
      env:
        IMAGE_TAG: "${{ inputs.image-tag }}"
        INSTALL_AWSLOCAL: "${{ inputs.install-awslocal }}"
        USE_PRO: "${{ inputs.use-pro }}"
        CONFIGURATION: "${{ inputs.configuration }}"
