name: Shutdown Ephemeral Instance
description: 'Shutdowns an Ephemeral Instance (PR Preview)'

inputs:
  localstack-auth-token:
    description: 'LocalStack Auth Token used to access the platform api'
    required: false
  github-token:
    description: 'Github token used to create PR comments'
    required: true
    

runs:
  using: composite
  steps:
    - name: Download PR artifact
      uses: actions/download-artifact@v4
      with:
        name: pr-id

    - name: Load the PR ID
      id: pr
      shell: bash
      run: echo "pr_id=$(<pr-id.txt)" >> $GITHUB_OUTPUT

    - name: Setup preview name
      shell: bash
      run: |
        prId=$(<pr-id.txt)
        repoName=$GITHUB_REPOSITORY
        repoNameCleaned=$(echo -n "$repoName" | tr -c '[:alnum:]' '-')
        previewName=preview-$repoNameCleaned-$prId
        echo "previewName=$previewName" >> $GITHUB_ENV

    - name: Shutdown ephemeral instance
      shell: bash
      run: |
        AUTH_HEADER="ls-api-key: ${LOCALSTACK_AUTH_TOKEN:-${LOCALSTACK_API_KEY:-${{ inputs.localstack-auth-token }}}}"
        CONTENT_TYPE_HEADER="content-type: application/json"
        API_URL_BASE="https://api.localstack.cloud/v1/compute/instances"

        retry() {
            local retries=5
            local count=0
            local wait=5
            while [ $count -lt $retries ]; do
                "$@"
                local exit_code=$?
                if [ $exit_code -eq 0 ]; then
                    return 0
                fi
                count=$((count + 1))
                echo "Command failed with exit code $exit_code. Retrying in $wait seconds... ($count/$retries)"
                sleep $wait
            done
            echo "Command failed after $retries retries."
            return 1
        }

        shutdown_instance() {
            http_code=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
                -H "$AUTH_HEADER" \
                -H "$CONTENT_TYPE_HEADER" \
                "$API_URL_BASE/$previewName")
            if [[ "$http_code" -ne 200 && "$http_code" -ne 404 ]]; then
                echo "Unable to delete preview environment. API returned HTTP code: $http_code"
                return 1
            fi
        fi
        retry shutdown_instance
    
    - name: Update status comment
      uses: actions-cool/maintain-one-comment@v3.1.1
      with:
        token: ${{ inputs.github-token }}
        body: |
          The ephemeral instance for the application preview has been shut down
          <!-- Sticky Pull Request Comment -->
        body-include: '<!-- Sticky Pull Request Comment -->'
        number: ${{ steps.pr.outputs.pr_id }}
