name: Shutdown Ephemeral Instance

inputs:
  localstack-api-key:
    description: 'LocalStack API key used to access the platform api'
    required: true
  github-token:
    description: 'Github token used to create PR comments'
    required: true
    

runs:
  using: composite
  steps:
    - name: Download PR artifact
      uses: actions/download-artifact@v4
      with:
        name: pr-id

    - name: Load the PR ID
      id: pr
      shell: bash
      run: echo "pr_id=$(<pr-id.txt)" >> $GITHUB_OUTPUT

    - name: Setup preview name
      shell: bash
      run: |
        prId=$(<pr-id.txt)
        repoName=$GITHUB_REPOSITORY
        repoNameCleaned=$(echo -n "$repoName" | tr -c '[:alnum:]' '-')
        previewName=preview-$repoNameCleaned-$prId
        echo "previewName=$previewName" >> $GITHUB_ENV

    - name: Shutdown ephemeral instance
      shell: bash
      run: |
        response=$(curl -X DELETE \
            -s -o /dev/null -w "%{http_code}" \
            -H "ls-api-key: ${LOCALSTACK_API_KEY:-${{ inputs.localstack-api-key }}}" \
            -H "content-type: application/json" \
            https://api.localstack.cloud/v1/compute/instances/$previewName)
        if [[ "$response" -ne 200 ]]; then
          # In case the deletion fails, e.g. if the instance cannot be found, we raise a proper error on the platform
          echo "Unable to delete preview environment. API response: $response"
          exit 1
        fi
    
    - name: Update status comment
      uses: actions-cool/maintain-one-comment@v3.1.1
      with:
        token: ${{ inputs.github-token }}
        body: |
          The ephemeral instance for the application preview has been shut down
          <!-- Sticky Pull Request Comment -->
        body-include: '<!-- Sticky Pull Request Comment -->'
        number: ${{ steps.pr.outputs.pr_id }}
