name: Finish CI Build

on:
  workflow_run:
    workflows: ["Run CI Tests"]
    types:
      - completed

inputs:
  github_token:
    description: 'Github token used to create PR comments'
    required: true

runs:
  using: composite
  steps:
    # if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    - name: Download PR artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        name: pr

    - name: Load the PR ID
      id: pr
      shell: bash
      run: echo "pr_id=$(<pr-id.txt)" >> $GITHUB_OUTPUT

    - name: Update status comment
      uses: actions-cool/maintain-one-comment@v3.1.1
      with:
        token: ${{ inputs.github_token }}
        body: |
          🚀 LocalStack Stack Insights and Cloud Pod state for this CI run: https://app.localstack.cloud/ci
          <!-- Sticky Pull Request Comment -->
        body-include: '<!-- Sticky Pull Request Comment -->'
        number: ${{ steps.pr.outputs.pr_id }}

  # failed:
  #   runs-on: ubuntu-latest
  #   if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'failure'
  #   steps:
  #
  #     - name: Save the PR ID
  #       id: pr
  #       run: echo "::set-output name=id::$(<pr-id.txt)"
  #
  #     - name: Job failure
  #       uses: actions-cool/maintain-one-comment@v3.1.1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         body: |
  #           Deploy PR Preview failed.
  #           <!-- Sticky Pull Request Comment -->
  #         body-include: '<!-- Sticky Pull Request Comment -->'
  #         number: ${{ steps.pr.outputs.id }}
