name: Create PR Preview

inputs:
  github-token:
    description: 'Github token used to create PR comments'
    required: true
  localstack-api-key:
    description: 'LocalStack API key used to create the preview environment'
    required: false
  preview-cmd:
    description: 'Command(s) used to create a preview of the PR (can use $AWS_ENDPOINT_URL)'
    required: false
    default: ''
  auto-load-pod:
    description: 'The pod to load on startup of LocalStack, the env var AUTO_LOAD_POD'
    required: false
    default: ''
  extension-auto-install:
    description: 'The extension(s) to automatically install onf startup of LocalStack, the env var EXTENSION_AUTO_INSTALL'
    required: false
  

runs:
  using: composite
  steps:
    - run: >
        echo "GH_ACTION_ROOT=$(
          ls -d $(
            ls -d ./../../_actions/* |
            grep -i localstack |
            tail -n1
          )/setup-localstack/* | 
          grep -v completed | 
          tail -n1
        )" >> $GITHUB_ENV
      shell: bash

    - name: Initial PR comment
      if: inputs.github-token
      uses: jenseng/dynamic-uses@v1
      with:
        uses: ${{ env.GH_ACTION_ROOT }}/prepare
        with: |-
          {
            "github-token": ${{ toJSON(inputs.github-token) }}
          }

    - name: Download PR artifact
      uses: actions/download-artifact@v3
      with:
        name: pr

    - name: Create preview environment
      shell: bash
      run: |
        prId=$(<pr-id.txt)
        # TODO: make preview name configurable!
        previewName=preview-$prId

        response=$(curl -X POST -d "{'env_vars': {'auto_load_pod': '${AUTO_LOAD_POD:-${{ inputs.auto-load-pod }}}', 'extension_auto_install': '${EXTENSION_AUTO_INSTALL:-${{ inputs.extension-auto-install }}}'}, 'instance_name': '${previewName}'}" \
            -H "ls-api-key: ${LOCALSTACK_API_KEY:-${{ inputs.localstack-api-key }}}" \
            -H "content-type: application/json" \
            https://api.staging.aws.localstack.cloud/v1/compute/instances/)
        endpointUrl=$(echo "$response" | jq -r .endpoint_url)
        if [ "$endpointUrl" = "null" ] || [ "$endpointUrl" = "" ]; then
          echo "Unable to create preview environment. API response: $response"
          exit 1
        fi
        echo "Created preview environment with endpoint URL: $endpointUrl"

        echo $endpointUrl > ./ls-preview-url.txt
        echo "LS_PREVIEW_URL=$endpointUrl" >> $GITHUB_ENV
        echo "AWS_ENDPOINT_URL=$endpointUrl" >> $GITHUB_ENV

    - name: Upload preview instance URL
      uses: actions/upload-artifact@v3
      with:
        name: pr
        path: ./ls-preview-url.txt

    - name: Run preview deployment
      if: ${{ inputs.preview-cmd != '' }}
      shell: bash
      run:
        ${{ inputs.preview-cmd }}
