name: Create PR Preview
description: 'Spins up an Ephemeral Instance for a PR Preview'

inputs:
  github-token:
    description: 'Github token used to create PR comments'
    required: true
  localstack-auth-token:
    description: 'LocalStack Auth Token used to create the preview environment'
    required: false
  preview-cmd:
    description: 'Command(s) used to create a preview of the PR (can use $AWS_ENDPOINT_URL)'
    required: false
    default: ''
  auto-load-pod:
    description: 'The pod to load on startup of LocalStack, the env var AUTO_LOAD_POD'
    required: false
    default: ''
  extension-auto-install:
    description: 'The extension(s) to automatically install on startup of LocalStack, the env var EXTENSION_AUTO_INSTALL'
    required: false
    default: ''
  lifetime:
    description: 'The lifetime of the ephemeral instance, how long the instance should be available for'
    required: false
    default: '30'
  

runs:
  using: composite
  steps:
    - run: >
        echo "GH_ACTION_ROOT=$(
          ls -d $(
            ls -d ./../../_actions/* |
            grep -i localstack |
            tail -n1
          )/setup-localstack/* | 
          grep -v completed | 
          tail -n1
        )" >> $GITHUB_ENV
      shell: bash

    - name: Initial PR comment
      if: inputs.github-token
      uses: jenseng/dynamic-uses@5175289a9a87978dcfcb9cf512b821d23b2a53eb # v1
      with:
        uses: ${{ env.GH_ACTION_ROOT }}/prepare
        with: |-
          {
            "github-token": ${{ toJSON(inputs.github-token) }}
          }

    - name: Download PR artifact
      uses: actions/download-artifact@v4
      with:
        name: pr-id

    - name: Setup preview name
      shell: bash
      id: preview-name
      run: |
        prId=$(<pr-id.txt)
        repoName=$GITHUB_REPOSITORY
        repoNameCleaned=$(echo -n "$repoName" | tr -c '[:alnum:]' '-')
        previewName=preview-$repoNameCleaned-$prId
        echo "previewName=$previewName" >> $GITHUB_ENV
        echo "name=$previewName" >> $GITHUB_OUTPUT

    - name: Create preview environment
      shell: bash
      id: create-instance
      run: |
        AUTH_HEADER="ls-api-key: ${LOCALSTACK_AUTH_TOKEN:-${LOCALSTACK_API_KEY:-${{ inputs.localstack-auth-token }}}}"
        CONTENT_TYPE_HEADER="content-type: application/json"
        API_URL_BASE="https://api.localstack.cloud/v1/compute/instances"

        retry() {
            local retries=5
            local count=0
            local wait=5
            while [ $count -lt $retries ]; do
                "$@"
                local exit_code=$?
                if [ $exit_code -eq 0 ]; then
                    return 0
                fi
                count=$((count + 1))
                echo "Command failed with exit code $exit_code. Retrying in $wait seconds... ($count/$retries)"
                sleep $wait
            done
            echo "Command failed after $retries retries."
            return 1
        }

        fetch_instances() {
            list_response=$(curl --fail-with-body -X GET \
                -H "$AUTH_HEADER" \
                -H "$CONTENT_TYPE_HEADER" \
                "$API_URL_BASE")
            if ! echo "$list_response" | jq -e 'type == "array"' > /dev/null; then
                echo "API returned an error: $list_response"
                return 1
            fi
        }

        retry fetch_instances

        autoLoadPod="${AUTO_LOAD_POD:-${{ inputs.auto-load-pod }}}"
        extensionAutoInstall="${EXTENSION_AUTO_INSTALL:-${{ inputs.extension-auto-install }}}"
        lifetime="${{ inputs.lifetime }}"

        instance_exists=$(echo "$list_response" | jq --arg NAME "$previewName" '.[] | select(.instance_name == $NAME)')

        delete_instance() {
            # We expect a 200 on success or 404 if it's already gone. Other codes are errors.
            http_code=$(curl -o /dev/null -w "%{http_code}" -X DELETE \
                -H "$AUTH_HEADER" \
                -H "$CONTENT_TYPE_HEADER" \
                "$API_URL_BASE/$previewName")
            if [ "$http_code" -ne 200 ] && [ "$http_code" -ne 404 ]; then
                echo "Error deleting instance, HTTP code: $http_code"
                return 1
            fi
        }

        if [ -n "$instance_exists" ]; then
          retry delete_instance
        fi

        create_instance_func() {
            response=$(curl --fail-with-body -X POST -d "{\"instance_name\": \"${previewName}\", \"lifetime\": ${lifetime} ,\"env_vars\": {\"AUTO_LOAD_POD\": \"${autoLoadPod}\", \"EXTENSION_AUTO_INSTALL\": \"${extensionAutoInstall}\"}}"\
                -H "$AUTH_HEADER" \
                -H "$CONTENT_TYPE_HEADER" \
                "$API_URL_BASE")
            
            endpointUrl=$(echo "$response" | jq -r .endpoint_url)
            if [ "$endpointUrl" = "null" ] || [ "$endpointUrl" = "" ]; then
              echo "Unable to create preview environment. API response: $response"
              return 1
            fi
        }

        retry create_instance_func

        echo "Created preview environment with endpoint URL: $endpointUrl"

        echo $endpointUrl > ./ls-preview-url.txt
        echo "LS_PREVIEW_URL=$endpointUrl" >> $GITHUB_ENV
        echo "AWS_ENDPOINT_URL=$endpointUrl" >> $GITHUB_ENV

    - name: Upload preview instance URL
      uses: actions/upload-artifact@v4
      with:
        name: preview-instance-url
        path: ./ls-preview-url.txt

    - name: Run preview deployment
      if: ${{ inputs.preview-cmd != '' }}
      shell: bash
      run: |
        ${{ inputs.preview-cmd }}

    - name: Print logs of ephemeral instance
      if: ${{ !cancelled() && steps.create-instance.outcome == 'success' }}
      shell: bash
      env:
        previewName: ${{ steps.preview-name.outputs.name }}
      run: |
        AUTH_HEADER="ls-api-key: ${LOCALSTACK_AUTH_TOKEN:-${LOCALSTACK_API_KEY:-${{ inputs.localstack-auth-token }}}}"
        CONTENT_TYPE_HEADER="content-type: application/json"
        API_URL_BASE="https://api.localstack.cloud/v1/compute/instances"

        # TODO code duplication
        retry() {
            local retries=5
            local count=0
            local wait=5
            while [ $count -lt $retries ]; do
                "$@"
                local exit_code=$?
                if [ $exit_code -eq 0 ]; then
                    return 0
                fi
                count=$((count + 1))
                echo "Command failed with exit code $exit_code. Retrying in $wait seconds... ($count/$retries)"
                sleep $wait
            done
            echo "Command failed after $retries retries."
            return 1
        }

        fetch_logs() {
            log_response=$(curl --fail-with-body -s -X GET \
                -H "$AUTH_HEADER" \
                -H "$CONTENT_TYPE_HEADER" \
                "$API_URL_BASE/$previewName/logs")
        }

        retry fetch_logs
        echo "$log_response" | jq -r '.[].content'
